[build]
command = "npx auralog build"
publish = "dist"

[build.processing]
skip_processing = true

[[redirects]]
from = "https://auralog.netlify.com/*"
to = "https://auralog.troyv.dev/:splat"
status = 301
force = true

[[headers]]
for = "/*"
[headers.values]
X-Content-Type-Options = "nosniff"
X-Frame-Options = "SAMEORIGIN"
X-XSS-Protection = "1"
