export default {
  html: {
    title: "Aura Log",
    meta: [
      {
        name: "description",
        content: "My migraine log and dashboard.",
      },
      {
        name: "theme-color",
        content: "#000000",
      },
    ],
  },
  contentDir: "entries",
  medications: ["Excedrin", "Ubrelvy", "Eletriptan", "None"],
  painAreas: [
    "Front Left",
    "Front Right",
    "Back Left",
    "Back Right",
    "Left Eye",
    "Right Eye",
  ],
  parseJournal: false,
  symptoms: [
    "Throbbing Pain",
    "Nausea",
    "Light Sensitivity",
    "Noise Sensitivity",
    "Blurred Vision",
    "Fatigue",
    "Neck Pain",
  ],
  triggers: [
    "Stress",
    "Don't Know",
    "Weather",
    "Lack of Sleep",
    "Rebound",
    "Processed Foods",
    "Anxiety",
    "Alcohol",
    "Dehydration",
    "Fever",
    "Screen Time",
    "Caffeine",
    "Sun",
    "Hunger",
  ],
};
